---
title: "Kulturförderung der Stadt Uster"
output: 
  flexdashboard::flex_dashboard:

    vertical_layout: fill
    theme: journal
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(RCurl)
library(knitr)
library(dplyr)
library(shiny)
daten <- read.csv("https://raw.githubusercontent.com/GesellschaftStadtUster/kultur_foerderbeitrage/main/daten_kulturfoerderung_uster.csv")

daten <- daten %>% arrange(desc(DatumEntscheid))
ubersichtdaten <- daten


```


Einleitung {.sidebar}
-----------------------------------------------------------------------

<b>Hier findest du eine Liste sowie Auswertungen zu den Kulturförderbeiträgeder Stadt Uster (seit 2018). Bitte beachte, dass es nach dem Förderentscheid einige Wochen dauern kann, bis die Daten aktualisiert werden.</b>

```{r}

auswahlbereich <- as.list(c("ALLE BEREICHE",names(table(daten$Foerderbereich))))

auswahljahr<- as.list(c("ALLE JAHRE",names(table(format(as.Date(daten$DatumEntscheid), "%Y")))))

auswahlfoerderart<- as.list(c("ALLE FOERDERARTEN",names(table(daten$Foerderart))))


selectInput("plot_bereich",  label = "Förderbereich:", 
                             choices = auswahlbereich, selected = 1)


selectInput("plot_jahr",  label = "Jahr:", 
                             choices = auswahljahr, selected = 1)


selectInput("plot_foerderart",  label = "Förderart:", 
                             choices = auswahlfoerderart, selected = 1)
```
<br>
<b>Datengrundlage</b><br>
Die Auswertung basiert auf [offenen Daten der Stadt Uster](https://opendata.swiss/de/dataset/beitrage-der-kulturforderung-der-stadt-uster-ab-2018). Die Daten stehen unter [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) zur Verfügung.
<br><br>
<b>Auswertung</b><br>
Die [Auswertung](https://github.com/socialthink/uster_kulturbericht) wurde von [Andreas Wyss](https://github.com/socialthink/) auf Grundlage von R entwickelt und steht unter einer [MIT Lizenz](https://github.com/socialthink/uster_kulturbericht/blob/master/LICENSE) zur Verfügung.



Row 
-----------------------------------------------------------------------

### {.no-mobile}

```{r}

renderPlot({
  
    if (input$plot_bereich=="ALLE BEREICHE") {
ubersichtdaten2 <- ubersichtdaten
} else {
ubersichtdaten2 <- ubersichtdaten %>% filter(Foerderbereich == input$plot_bereich)
}
  if (input$plot_jahr=="ALLE JAHRE") {
ubersichtdaten3 <- ubersichtdaten2
} else {
ubersichtdaten3 <- ubersichtdaten2 %>% filter(as.Date(DatumEntscheid) <= as.Date(paste0(input$plot_jahr,"-12-31"))) %>% filter(as.Date(DatumEntscheid) >= as.Date(paste0(input$plot_jahr,"-1-1")))
}
   if (input$plot_foerderart=="ALLE FOERDERARTEN") {
ubersichtdaten4 <- ubersichtdaten3
} else {
ubersichtdaten4 <- ubersichtdaten3 %>% filter(Foerderart == input$plot_foerderart)
} 
  
  

## Jahresbeiträge Summe berechnen
    
if(dim(ubersichtdaten4)[1]==0){
summe <- 0
anzahljahre <- 0
startjahr <- "keine Förderbeiträge\nmit dieser Auswahl"
} else {
ubersichtdaten4$DatumEntscheid <- as.Date(ubersichtdaten4$DatumEntscheid)
anzahljahre <- as.numeric(format(max(as.Date(ubersichtdaten4$DatumEntscheid)), format="%Y")) - as.numeric(format(min(as.Date(ubersichtdaten4$DatumEntscheid)), format="%Y"))
startjahr <- as.numeric(format(min(as.Date(ubersichtdaten4$DatumEntscheid)), format="%Y"))
wert <- ubersichtdaten4 %>% filter(DatumEntscheid >= as.Date(paste0(startjahr,"-01-01")) & DatumEntscheid <= as.Date(paste0(startjahr,"-12-31")))
summe <- sum(wert$FoerderbeitragCHF)
jahre <- startjahr
}

if (anzahljahre==0) {
jahre <- startjahr
} else {
for(i in 1:anzahljahre){
  wert <- ubersichtdaten4 %>% filter(DatumEntscheid >= as.Date(paste0(startjahr+i,"-01-01")) & DatumEntscheid <= as.Date(paste0(startjahr+i,"-12-31")))
  wert <- sum(wert$FoerderbeitragCHF)
  summe <- c(summe,wert)
  jahre <- c(jahre,startjahr+i)
}
}



## Plot

barplot(summe/1000,names.arg = jahre, ylim=c(0,600), main = "Summe pro Jahr", ylab = "Förderbeitrag pro Jahr [in 1'000 Franken]")
  

})


```


### {.no-mobile}

```{r}


renderPlot({
  
    if (input$plot_bereich=="ALLE BEREICHE") {
ubersichtdaten2 <- ubersichtdaten
} else {
ubersichtdaten2 <- ubersichtdaten %>% filter(Foerderbereich == input$plot_bereich)
}
  if (input$plot_jahr=="ALLE JAHRE") {
ubersichtdaten3 <- ubersichtdaten2
} else {
ubersichtdaten3 <- ubersichtdaten2 %>% filter(as.Date(DatumEntscheid) <= as.Date(paste0(input$plot_jahr,"-12-31"))) %>% filter(as.Date(DatumEntscheid) >= as.Date(paste0(input$plot_jahr,"-1-1")))
}
   if (input$plot_foerderart=="ALLE FOERDERARTEN") {
ubersichtdaten4 <- ubersichtdaten3
} else {
ubersichtdaten4 <- ubersichtdaten3 %>% filter(Foerderart == input$plot_foerderart)
} 
  
  
hist(ubersichtdaten4$FoerderbeitragCHF/1000, breaks=seq(0, max(daten$FoerderbeitragCHF)/1000, length.out = as.integer(max(daten$FoerderbeitragCHF)/5000)) ,xlim=c(0,max(daten$FoerderbeitragCHF)/1000), ylim=c(0,dim(daten)[1]) , xlab = "Förderbeiträge [in 1'000 Franken']",ylab = "Häufigkeit [Anz. Beiträge]", main = "Höhe der einzelnen Beiträge in der Kulturförderung")
})

```

Row 
-----------------------------------------------------------------------

### {.no-mobile}

```{r}
selectedDataUbersicht <- reactive({
  if (input$plot_bereich=="ALLE BEREICHE") {
ubersichtdaten2 <- ubersichtdaten
} else {
ubersichtdaten2 <- ubersichtdaten %>% filter(Foerderbereich == input$plot_bereich)
}
  if (input$plot_jahr=="ALLE JAHRE") {
ubersichtdaten3 <- ubersichtdaten2
} else {
ubersichtdaten3 <- ubersichtdaten2 %>% filter(as.Date(DatumEntscheid) <= as.Date(paste0(input$plot_jahr,"-12-31"))) %>% filter(as.Date(DatumEntscheid) >= as.Date(paste0(input$plot_jahr,"-1-1")))
}
   if (input$plot_foerderart=="ALLE FOERDERARTEN") {
ubersichtdaten4 <- ubersichtdaten3
} else {
ubersichtdaten4 <- ubersichtdaten3 %>% filter(Foerderart == input$plot_foerderart)
} 
  
  ubersichtdaten4$DatumEntscheid <- format(as.Date(ubersichtdaten4$DatumEntscheid), "%d.%m.%Y")
  ubersichtdaten4
})
renderTable({
  selectedDataUbersicht()
})
```