---
title: "Kulturförderung der Stadt Uster"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: journal
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(RCurl)
library(knitr)
library(dplyr)
daten <- read.csv("https://raw.githubusercontent.com/GesellschaftStadtUster/kultur_foerderbeitrage/main/daten_kulturfoerderung_uster.csv")

daten <- daten %>% arrange(desc(DatumEntscheid))
ubersichtdaten <- daten


```

Übersicht
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

Hier finden Sie eine Liste aller Kulturförderbeiträge seit 2018. Bitte beachten Sie, dass es nach dem Förderentscheid einige Wochen dauern kann, bis die Daten aktualisiert wurden.

```{r}
auswahlbereich <- as.list(c("ALLE BEREICHE",names(table(daten$Foerderbereich))))

selectInput("ubersicht_bereich",  label = "Förderbereich:", 
                             choices = auswahlbereich, selected = 1)

auswahljahr<- as.list(c("ALLE JAHRE",names(table(format(as.Date(daten$DatumEntscheid), "%Y")))))

selectInput("ubersicht_jahr",  label = "Jahr:", 
                             choices = auswahljahr, selected = 1)

auswahlfoerderart<- as.list(c("ALLE FOERDERARTEN",names(table(daten$Foerderart))))

selectInput("ubersicht_foerderart",  label = "Jahr:", 
                             choices = auswahlfoerderart, selected = 1)
```


Column 
-----------------------------------------------------------------------

### 

```{r}
selectedData <- reactive({
  if (input$ubersicht_bereich=="ALLE BEREICHE") {
ubersichtdaten2 <- ubersichtdaten
} else {
ubersichtdaten2 <- ubersichtdaten %>% filter(Foerderbereich == input$ubersicht_bereich)
}
  if (input$ubersicht_jahr=="ALLE JAHRE") {
ubersichtdaten3 <- ubersichtdaten2
} else {
ubersichtdaten3 <- ubersichtdaten2 %>% filter(as.Date(DatumEntscheid) <= as.Date(paste0(input$ubersicht_jahr,"-12-31"))) %>% filter(as.Date(DatumEntscheid) >= as.Date(paste0(input$ubersicht_jahr,"-1-1")))
}
   if (input$ubersicht_foerderart=="ALLE FOERDERARTEN") {
ubersichtdaten4 <- ubersichtdaten3
} else {
ubersichtdaten4 <- ubersichtdaten3 %>% filter(Foerderart == input$ubersicht_foerderart)
} 
  
  ubersichtdaten4$DatumEntscheid <- format(as.Date(ubersichtdaten4$DatumEntscheid), "%d.%m.%Y")
  ubersichtdaten4
})
renderTable({
  selectedData()
})
```

