---
title: "Kulturförderung der Stadt Uster"
output: 
  flexdashboard::flex_dashboard:

    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(RCurl)
library(knitr)
library(dplyr)
library(shiny)
daten <- read.csv("https://raw.githubusercontent.com/GesellschaftStadtUster/kultur_foerderbeitrage/main/daten_kulturfoerderung_uster.csv")

daten <- daten %>% arrange(desc(DatumEntscheid))
ubersichtdaten <- daten

```


Einleitung {.sidebar}
-----------------------------------------------------------------------

<b>Hier findest du eine Liste sowie Auswertungen zu den Kulturförderbeiträgeder Stadt Uster (seit 2018). Bitte beachte, dass es nach dem Förderentscheid einige Wochen dauern kann, bis die Daten aktualisiert werden.</b>

```{r}

auswahlbereich <- as.list(c("ALLE BEREICHE",names(table(daten$Foerderbereich))))

auswahljahr<- as.list(c("ALLE JAHRE",names(table(format(as.Date(daten$DatumEntscheid), "%Y")))))

auswahlfoerderart<- as.list(c("ALLE FOERDERARTEN",names(table(daten$Foerderart))))


selectInput("plot_bereich",  label = "Förderbereich:", 
                             choices = auswahlbereich, selected = 1)


selectInput("plot_jahr",  label = "Jahr:", 
                             choices = auswahljahr, selected = 1)


selectInput("plot_foerderart",  label = "Förderart:", 
                             choices = auswahlfoerderart, selected = 1)
```


Row 
-----------------------------------------------------------------------

###

```{r}
selectedDataUbersicht <- reactive({
  if (input$plot_bereich=="ALLE BEREICHE") {
ubersichtdaten2 <- ubersichtdaten
} else {
ubersichtdaten2 <- ubersichtdaten %>% filter(Foerderbereich == input$plot_bereich)
}
  if (input$plot_jahr=="ALLE JAHRE") {
ubersichtdaten3 <- ubersichtdaten2
} else {
ubersichtdaten3 <- ubersichtdaten2 %>% filter(as.Date(DatumEntscheid) <= as.Date(paste0(input$plot_jahr,"-12-31"))) %>% filter(as.Date(DatumEntscheid) >= as.Date(paste0(input$plot_jahr,"-1-1")))
}
   if (input$plot_foerderart=="ALLE FOERDERARTEN") {
ubersichtdaten4 <- ubersichtdaten3
} else {
ubersichtdaten4 <- ubersichtdaten3 %>% filter(Foerderart == input$plot_foerderart)
} 
  
  ubersichtdaten4$DatumEntscheid <- format(as.Date(ubersichtdaten4$DatumEntscheid), "%d.%m.%Y")
  ubersichtdaten4
})
renderTable({
  selectedDataUbersicht()
})
```